cfengine/documentation-generator

_config.yml

Update _config.yml for 3.7

---

_includes/header_nav.html

(cherry picked from commit 457943a6ee06a8b3257bd78257fbcf1315e7d1ed)

Add: Dropdown option for 3.7

---

_includes/footer.html

https://dev.cfengine.com/issues/7566

Fix: Link for offline version of documentation

---

README.md
_plugins/category_nav.rb
_plugins/debug.rb

Signed-off-by: Stefan Weil <sw@weilnetz.de>

Fix typos found by codespell

---

_config.yml

(cherry picked from commit 726f7cb0b5147a693290238653aa19f7ee636dfa)
Conflicts:
_config.yml

Add: CFEngine related data to site

---

_config.yml

This will make it easier to update docs that show working with the
latest package available.

Add: Package and Build data

---

_config.yml

This will enable the use of variables as done in master and 3.8 branches
recently.

Add: Site data for 3.7

---

_references.md

This reverts commit 18eb8b904eee51873ed34c3447c02996b048525a. It had no
effect on the build.

Revert "Add: Reference for `collecting functions`"

---

_assets/js/google_analytics_search.js
_config.yml
_includes/header_nav.html
_layouts/google_search.html

Liquify gcse code for easier updating

---

_regenerate_json.sh

Signed-off-by: Ole Herman Schumacher Elgesem <ole.elgesem@cfengine.com>

3.11: Added cf-net to --help generation

---

_scripts/_publish.sh

In the process to move stuff to the cloud, we'll use Jenkins to upload artefacts to buildcache, and later prod server will pull new stuff from buildcache

Collect everything in one dir instead of rsyncing everything

---

_scripts/_publish.sh

This should increase transfer speed to buildcache

tar whole _site, instead of copying

---

_regenerate_json.sh

(cherry picked from commit 80ddea4fad91382436c068401cda5db0a10fc4a2)

CFE-2370: Strip errors from single file policy -> json conversion

---

_scripts/_run_jekyll.sh

Unsure why we are deleting the .git repos here. At least for local development
this becomes problematic.

Dont destroy the git repo data

---

_config.yml

(cherry picked from commit ebba0e82e06fc7039ee9d4359b5eee44980b44d3)

Update the data for vagrant versions tested

---

_scripts/_run_jekyll.sh

This reverts commit
af67d08153b7e551cb3558e9621f1316c5b1ea62. Users are asking about
PDF version of our docs.

Revert "Disable pdf generation"

---

_references.md

(cherry picked from commit 580b1203a51385e62c0e05c3250b5eff04d7c067)

Add references to MPF configuration examples

---

_regenerate_json.sh

CFE-3619: Generated output from cf-promises --show-vars and --show-classes (master)

---

_assets/css/hacks.css

Temporarily add some very !important CSS

---

_regenerate_json.sh
_scripts/_run_jekyll.sh
_scripts/cfdoc_linkresolver.py

less Jenking jobs to create every 1.5 years!

ENT-5549 Build docs in pr-pipeline

---

_references.md

Ticket: CFE-3716
(cherry picked from commit 8adf851ad7eb9ad6aa353548c9509effd5e9535f)

CFE-3716: Added reference for MPF services/autorun (3.18)

---

_regenerate_json.sh
_scripts/_run_jekyll.sh
_scripts/cfdoc_linkresolver.py

(cherry picked from commit 13097f6192fadd082ecceb683bf185bba2e4c8a5)

ENT-5549 Build docs in pr-pipeline - 3.15

---

_regenerate_json.sh
_scripts/_run_jekyll.sh
_scripts/cfdoc_linkresolver.py

(cherry picked from commit 13097f6192fadd082ecceb683bf185bba2e4c8a5)
(cherry picked from commit ee8b69f87a413ee8230a6b7e21f36d31cebeef47)

ENT-5549 Build docs in pr-pipeline - 3.12

---

_regenerate_json.sh
_scripts/_run_jekyll.sh
_scripts/cfdoc_linkresolver.py

(cherry picked from commit 13097f6192fadd082ecceb683bf185bba2e4c8a5)

ENT-5549 Build docs in pr-pipeline - 3.18

---

_references.md

The wrong target resulted in redirection to the home page instead of the desired
page.
Ticket: ENT-7608

ENT-7608: Fixed reference for Classes and Decisions

---

_config.yml

ENT-7876: Updated versions after release of 3.18.1 (3.18)

---

_config.yml

ENT-7830: Update versions after release of 3.15.5 (3.15)

---

_scripts/_publish.sh

so it's possible to have docs preview just by visiting this URL:
http://buildcache.cloud.cfengine.com/packages/build-documentation-pr/267/jenkins-pr-pipeline-7202/output/_site/
(cherry picked from commit ad361e6a0863757267774b8a07e30507f3798733)

make assets links relative - master

---

build/Dockerfile
build/README.md
build/install.sh
build/main.sh
build/run.sh

Disclaimer: `install.sh` and `main.sh` scripts are mostly copy-pasted form Jenkins config, with minor modifications like:
* not installing stuff required for building CFEngine
* unpacking CFEngine *.deb file instead of installing it

Build docs in a container

---

build/Dockerfile
build/README.md
build/install.sh
build/main.sh
build/run.sh

(cherry picked from commit 3f6b1f728d3fd0c965e06a8241660584bab4c6b7)

Add scripts to build docs in a container - 3.18

---

build/Dockerfile
build/README.md
build/install.sh
build/main.sh
build/run.sh

(cherry picked from commit 3f6b1f728d3fd0c965e06a8241660584bab4c6b7)

Add scripts to build docs in a container - 3.15

---

build/run.sh

Otherwise, they can't be deleted afterwards

Relax permissions for cleanup

---

build/latest_nightly.sh

Add a script to auto-detect latest build

---

build/latest_nightly.sh

Ticket: ENT-8401
(cherry picked from commit 7e2b833cf30e640fd5903c156c9633b02c076923)

Add a script to auto-detect latest build - 3.18

---

_config.yml

(cherry picked from commit 56e1930f3a5ce0a27a9d08ef4cfd6ca88fb63162)
(cherry picked from commit 5ac1e102df2dc223557fcabb8f26fd0ee7f75122)

Set git-branch

---

_regenerate_json.sh

ENT-8885: Added dumping help output for cf-reactor

---

_layouts/google_search.html
build/search/createIndex.js

Changed search page layout

---

_assets/css/hacks.css
_assets/css/navigation.css
_assets/css/style.css
_assets/js/custom.js
_includes/head.html

Added copy to clipboard button to code elements & Implemented new content styles (master)

---

build/main.sh

Fixed docs building

---

_plugins/navigation.rb

There are not published top level pages which cause error during docs generation
Ticket: ENT-9036

Fixed navigation plugin

---

_layouts/default.html
build/main.sh

Use a real docs branch version instead of CFEngine version

Fixed `suggest changes` links

---

_plugins/navigation.rb
build/search/createIndex.js

Sort left navigation by sorting column and title & Fixed search index
