- _plugins/sitemap_generator.rb
This seems to be generated for pages that are unpublished. This makes
the condition a bit more clear.
> Change: Error message for missing ALIAS

- _config.yml
latest_patch_release was rendering as 1, instead of 0b1.
> Attempt to fix link in vagrant docs

- _references.md
Trying to fix the doc build which was broken around the time this new
section was added. Build errors with <unknown> key from
`_plugins/references.rb`
> Add: Reference for `collecting functions`

- _references.md
sys.fqhost links to sys.uqhost, but the link is broken. Probably because it
falls later on the same page and it isn't properly resolved. We have had to do
similar for sys.policy_entry_dirname and sys.policy_entry_filename in the past.
This change adds a reference link for sys.uqhost so that it will be sure to
resolve.
> CFE-2965 Add link reference to sys.uqhost

- _scripts/cfdoc_macros.py
dict.keys() in Python returns the keys in a random order so if we
use the keys as column names in a tables, we should explicitly
sort them.
> Sort columns in tables generated from dicts

- _references.md
This target is linked to from the page it's on, but before it, so it needs a
reference to be able to find it.
Ticket: CFE-1962
> CFE-1962: Added reference for mpf_extra_autorun_inputs (master)

- _references.md
This target is linked to from the page it's on, but before it, so it needs a
reference to be able to find it.
Ticket: CFE-1962
(cherry picked from commit f0912d4bd3182d6f01e398768101272657531e37)
> CFE-1962: Added reference for mpf_extra_autorun_inputs (3.15)

- _references.md
The wrong target resulted in redirection to the home page instead of the desired
page.
Ticket: ENT-7608
(cherry picked from commit a273145235cc1877d8e528105c87ff8cc6139130)
> ENT-7608: Fixed reference for Classes and Decisions (3.18)

- _references.md
The wrong target resulted in redirection to the home page instead of the desired
page.
Ticket: ENT-7608
(cherry picked from commit a273145235cc1877d8e528105c87ff8cc6139130)
> ENT-7608: Fixed reference for Classes and Decisions (3.15)

- _scripts/_publish.sh
so it's possible to have docs preview just by visiting this URL:
http://buildcache.cloud.cfengine.com/packages/build-documentation-pr/267/jenkins-pr-pipeline-7202/output/_site/
(cherry picked from commit ad361e6a0863757267774b8a07e30507f3798733)
> make assets links relative - 3.15

- _scripts/_publish.sh
so it's possible to have docs preview just by visiting this URL:
http://buildcache.cloud.cfengine.com/packages/build-documentation-pr/267/jenkins-pr-pipeline-7202/output/_site/
(cherry picked from commit ad361e6a0863757267774b8a07e30507f3798733)
> make assets links relative - 3.19

- _assets/css/style.css
> Centered images in docs

- build/run.sh
Issue was that job running inside the container needs to have write
permissions to some dirs. Easiest to achive this is by `chown`'ing
everything to the "jenkins" user inside the container. But then workdir
can't be cleaned up afterwards by "jenkins" user outside the container!
Solution is to chmod a+rwX everything before cleanup.
(cherry picked from commit 9f8be3ab922d804f3c59023361861594f37f4c6b)
> Relax permissions for cleanup - 3.18

- build/run.sh
Issue was that job running inside the container needs to have write
permissions to some dirs. Easiest to achive this is by `chown`'ing
everything to the "jenkins" user inside the container. But then workdir
can't be cleaned up afterwards by "jenkins" user outside the container!
Solution is to chmod a+rwX everything before cleanup.
(cherry picked from commit 9f8be3ab922d804f3c59023361861594f37f4c6b)
> Relax permissions for cleanup - 3.15

- _scripts/cfdoc_bootstrap.py
- _scripts/cfdoc_environment.py
- _scripts/cfdoc_git.py
- _scripts/cfdoc_macros.py
- _scripts/cfdoc_metadata.py
- _scripts/cfdoc_patch_header_nav.py
- _scripts/cfdoc_postprocess.py
- _scripts/cfdoc_preprocess.py
- _scripts/cfdoc_printsource.py
- _scripts/cfdoc_qa.py
- _scripts/cfdoc_sourcelinks.py
- build/Dockerfile
- build/install.sh
- build/main.sh
- build/run.sh
Ticket: ENT-8470
Changes:
* make install script fail on error (set -e)
* use gpg2 instead of gpg
* install ruby without rubygems (before rvm tried to install rubygems
and failed and we ignored it)
* install ruby without openssl (because ruby compiled against openssl
1.0 and modern distros don't ship it. And we don't need openssl in
ruby anyway)
* use python3 instead of python2
* Changed Python scripts from 2 to 3 using 2to3.py
> Update docs container to Ubuntu 22

- build/main.sh
(cherry picked from commit 4545ce83167244c546cd1a22a7dd875b2a0c73fa)
> Fixed docs building (3.20)

- build/main.sh
(cherry picked from commit 4545ce83167244c546cd1a22a7dd875b2a0c73fa)
> Fixed docs building (3.18)

- build/main.sh
(cherry picked from commit 4545ce83167244c546cd1a22a7dd875b2a0c73fa)
> Fixed docs building (3.15)

- build/main.sh
(cherry picked from commit 4545ce83167244c546cd1a22a7dd875b2a0c73fa)
> Fixed docs building (revamp)

- _scripts/cfdoc_macros.py
When de-indenting some code blocks I found that for the purposes
of our macros and auto-linking magic, we will consider lines
starting with # as markdown headings / titles, even when they
are inside triple-backticked code blocks.
This should be fixed, but I anticipate the fix might cause some
problems. (Maybe).
> Avoid creating titles inside code blocks
